# Generated by Django 3.0.6 on 2020-06-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientNum', models.TextField(max_length=100, verbose_name='客户端号')),
                ('score', models.IntegerField(max_length=10000000, verbose_name='得分')),
            ],
            options={
                'ordering': ('score',),
            },
        ),
    ]
