# Generated by Django 3.0.6 on 2020-06-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateScore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(verbose_name='得分'),
        ),
    ]
